name: CI
on: [push, pull_request]

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Components
        run: npm install

      - name: Run Rocket Pool tests
        run: npm test
